name: Auto Pull on Update

on:
  push:
    branches:
      - main  # 或者你想要监听的分支

jobs:
  pull-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: towerstreet/IPTV-TVBOX
          token: ${{ secrets.GITHUB_TOKEN }}
          path: /home/towerstreet/Storage/.git/IPTV-TVBOX

      - name: Pull Latest Changes
        run: |
          cd /home/towerstreet/Storage/.git/IPTV-TVBOX
          git pull origin main  # 或者你想要拉取的分支
