name: IPTV_m3u

on:
  push:
    branches:
      - main
  schedule:
    - cron: '40 * * * *'

jobs:
  IPTV_m3u:
    runs-on: ubuntu-latest
    env:
      HAS_CHANGES: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Pull
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git pull origin main

    - name: Download M3U Files
      run: |
        curl -o ipv6.m3u https://raw.githubusercontent.com/fanmingming/live/refs/heads/main/tv/m3u/ipv6.m3u
        curl -o Global.m3u https://raw.githubusercontent.com/YueChan/Live/refs/heads/main/Global.m3u
        curl -o Radio.m3u https://raw.githubusercontent.com/YueChan/Live/refs/heads/main/Radio.m3u

    - name: Merge M3U Files
      run: cat ipv6.m3u Global.m3u Radio.m3u > IPTV.m3u

    - name: Delete Original M3U Files
      run: |
        rm -f ipv6.m3u
        rm -f Global.m3u
        rm -f Radio.m3u

    - name: Check for changes and commit
      run: |
        git add IPTV.m3u
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          echo "HAS_CHANGES=true" >> $GITHUB_ENV
          git commit -m '$(date +"%F %r")'
          git push origin main
        fi

    - name: Send notification to Gotify
      if: env.HAS_CHANGES == 'true'
      run: |
        curl -X POST "{{secrets.GOTIFY_URL}}/message?token={{secrets.GOTIFY_TOKEN}}" \
        -F "title=🤖IPTV M3U Updated" \
        -F "message=The IPTV M3U file has been updated." \
        -F "priority=9"
