name: Merge M3U Files

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  merge-m3u:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download M3U Files
      run: |
        curl -o ipv6.m3u https://raw.githubusercontent.com/fanmingming/live/refs/heads/main/tv/m3u/ipv6.m3u
        curl -o Global.m3u https://raw.githubusercontent.com/YueChan/Live/refs/heads/main/Global.m3u
        curl -o Radio.m3u https://raw.githubusercontent.com/YueChan/Live/refs/heads/main/Radio.m3u

    - name: Merge M3U Files
      run: |
        cat ipv6.m3u Global.m3u Radio.m3u > IPTV.m3u

    - name: Delete Original M3U Files
      run: |
        rm -f ipv6.m3u
        rm -f Global.m3u
        rm -f Radio.m3u

    - name: Commit and push merged file
      id: commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add IPTV.m3u
        git commit -m 'Merge M3U files into IPTV.m3u' || echo "No changes to commit"
        if [ $? -eq 0 ]; then
          git push
          echo "COMMIT_STATUS=success" >> $GITHUB_ENV
        else
          echo "COMMIT_STATUS=failure" >> $GITHUB_ENV
        fi

    - name: Send notification to Gotify
      if: steps.commit.outputs.COMMIT_STATUS == 'success'
      env:
        GOTIFY_URL: ${{ secrets.GOTIFY_URL }}
        GOTIFY_TOKEN: ${{ secrets.GOTIFY_TOKEN }}
      run: |
        curl -X POST "$GOTIFY_URL" \
        -H "X-Gotify-Key: $GOTIFY_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{
          "title": "GITHUB ACTIONS🤖",
          "message": "# IPTV.m3u \n\nThe M3U files have been successfully merged and pushed to the [_repository_](https://github.com/towerstreet/IPTV-TVBOX)",
          "priority": 6,
          "extras": {
            "client::display": {
              "contentType": "text/markdown"
            }
          }
        }'
