name: Sync fanmingming/live ipv6.m3u

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch fanmingming/live ipv6.m3u
        run: |
          curl -L -o IPTV.m3u https://github.com/fanmingming/live/raw/refs/heads/main/tv/m3u/ipv6.m3u
          if ! git diff --quiet ipv6.m3u IPTV.m3u; then
            echo "File has changed, creating a PR"
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add IPTV.m3u
            git commit -m "Sync fanmingming/live ipv6.m3u"
            git push origin main
            gh pr create --title "Sync fanmingming/live ipv6.m3u" --body "Automated sync of file from remote repo"
          else
            echo "File has not changed"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
